config/routes.rb
Rails.application.routes.draw do
  resources :assign_rental_items do
    collection do
      get 'item_list'
    end
  end

  get 'health_check_pages/cooking'
  get 'health_check_pages/no_cooking'

  get 'stool_test_pages/check_sheet'
  get 'stool_test_pages/for_examiner_sheet'
  get 'stool_test_pages/for_health_center_sheet'

  resources :group_project_names
  resources :stage_common_options
  resources :rentable_items
  resources :stocker_items
  resources :sub_reps
  resources :purchase_lists do
    collection do
      get 'index_cooking'
      get 'new_cooking'
      get 'index_noncooking'
      get 'new_noncooking'
    end
  end
  resources :shops
  resources :food_products
  resources :employees
  resources :place_orders
  resources :stage_orders
  resources :power_orders
  resources :rental_orders
  resources :groups
  resources :user_details
  get 'welcome/index'
  get 'welcome/regist_user_detail'

  config = ActiveAdmin::Devise.config
  config[:controllers][:registrations] = 'registrations'
  devise_for :users, config
  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :group
  belongs_to :employee_category
  has_many :food_products, through: :group

  # before_save :give_duplication
  # before_destroy :remove_duplication # レコードのdelete後に実行

  validates_presence_of :group_id, :student_id, :name, :employee_category_id
  validates_numericality_of :group_id, :student_id, :employee_category_id, only_integer: true

  validates :student_id, format: { with: /(\A\d{8}+\z)/i }

  validates :student_id, :uniqueness => {:scope => [:group_id] } # 団体と学籍番号でユニーク

  # 同じ学籍番号が登録されていれば重複を記録する
  def give_duplication
    same_student_ids = Employee.where(student_id: self.student_id)
    if same_student_ids.length > 1 then
      # selfのレコード + 他のレコードがあれば
      same_student_ids.each do |record|
        record.duplication = true
      end
    else
      # それ以外なら
      self.duplication = false
    end
  end

  # 削除される学籍番号と同じものが1つのみDBにあれば，
  # そのレコードのduplicationをfalseにする
  def remove_duplication
    same_student_ids = Employee.where(student_id: self.student_id)
    if same_student_ids.length == 2 then
      # selfのレコード + 他のレコードがあれば
      same_student_ids.each do |record|
        record.duplication = false
      end
    end
  end

  # group_id, student_idでソート
  scope :sort_groupid_studentid, -> {order( :group_id, :student_id )}
  # 調理ありを検索するスコープ
  scope :cooking, -> {where( food_products: {is_cooking: 'true'} )}
  # 調理ありの提供品を扱う団体の従業員を取得
  scope :cooking_employees, -> (year_id) {
    joins( :food_products ).where( groups: { fes_year_id: year_id } ).cooking.sort_groupid_studentid.uniq
  }
end

app/controllers/employees_controller.rb
class EmployeesController < GroupBase
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :set_groups # カレントユーザの所有する団体を@groupsとする
  load_and_authorize_resource # for cancancan

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.where(group_id: @groups)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:group_id, :name, :student_id, :employee_category_id, :duplication)
    end

    def set_groups
      super  # set @groups by GroupBase.get_groups
      @groups = @groups.where( group_category_id: 1)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for @employee, wrapper: "horizontal_form", :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.association :group, collection: @groups, selected: @employee.group_id %>
  <%= error_span(@employee[:group_id]) %>

  <%= f.input :name, hint: t(".hint_name") %>
  <%= error_span(@employee[:name]) %>

  <%= f.input :student_id, hint: t(".hint_studentid") %>
  <%= error_span(@employee[:student_id]) %>

  <%= f.association :employee_category, hint: t(".hint_category") %>
  <%= error_span(@employee[:employee_category_id]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employees_path, :class => 'btn btn-default' %>
<% end %>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:group) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:student_id) %></th>
      <th><%= model_class.human_attribute_name(:employee_category) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.group.name %></td>
        <td><%= employee.name %></td>
        <td><%= employee.student_id %></td>
        <td><%= employee.employee_category %></td>
        <td>
          <%= show_edit_botton(edit_employee_path(employee), employee) %>
          <%= show_destroy_botton(employee_path(employee), employee) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.back', :default => t("helpers.links.back")),
              welcome_index_path, :class => 'btn btn-default'  %>
<%= show_new_with_group(Employee, new_employee_path) %>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:group) %>:</strong></dt>
  <dd><%= @employee.group.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @employee.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:student_id) %>:</strong></dt>
  <dd><%= @employee.student_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:employee_category) %>:</strong></dt>
  <dd><%= @employee.employee_category %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              employees_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_path(@employee), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_path(@employee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>