config/routes.rb
Rails.application.routes.draw do
  resources :assign_rental_items do
    collection do
      get 'item_list'
    end
  end

  get 'health_check_pages/cooking'
  get 'health_check_pages/no_cooking'

  get 'stool_test_pages/check_sheet'
  get 'stool_test_pages/for_examiner_sheet'
  get 'stool_test_pages/for_health_center_sheet'

  resources :group_project_names
  resources :stage_common_options
  resources :rentable_items
  resources :stocker_items
  resources :sub_reps
  resources :purchase_lists do
    collection do
      get 'index_cooking'
      get 'new_cooking'
      get 'index_noncooking'
      get 'new_noncooking'
    end
  end
  resources :shops
  resources :food_products
  resources :employees
  resources :place_orders
  resources :stage_orders
  resources :power_orders
  resources :rental_orders
  resources :groups
  resources :user_details
  get 'welcome/index'
  get 'welcome/regist_user_detail'

  config = ActiveAdmin::Devise.config
  config[:controllers][:registrations] = 'registrations'
  devise_for :users, config
  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/models/food_product.rb
class FoodProduct < ActiveRecord::Base
  belongs_to :group
  has_many :purchase_list
  has_many :employees, through: :group

  validates_presence_of :group_id, :name, :first_day_num, :second_day_num
  validates_numericality_of :group_id, :first_day_num, :second_day_num
  # boolean型をチェック. presence_of ではfalseでエラーになってしまう
  validates :is_cooking, inclusion: {in: [true, false]}

  def to_s
    self.name
  end

  def disp_cooking
    disp = self.is_cooking ? '調理あり' : '調理なし(提供のみ)'
    return disp
  end

  # グループidで検索するスコープ
  scope :groups, -> (group_ids) {where( group_id: group_ids )}
  # 調理ありを検索するスコープ
  scope :cooking, -> {where( is_cooking: 'true' )}
  # 調理なしを検索するスコープ
  scope :non_cooking, -> {where( is_cooking: 'false' )}

  scope :cooking_products, -> (year_id) {
      cooking.joins(:group => :fes_year).merge(Group.year_groups(year_id))}

  scope :non_cooking_products,  -> (year_id) {
      non_cooking.joins(:group => :fes_year).merge(Group.year_groups(year_id))}

end

app/controllers/food_products_controller.rb
class FoodProductsController < GroupBase
  before_action :set_food_product, only: [:show, :edit, :update, :destroy]
  before_action :set_groups # 各アクションの実行前に実行
  load_and_authorize_resource # for cancancan

  # GET /food_products
  # GET /food_products.json
  def index
    @food_products = FoodProduct.where(group_id: @groups)
  end

  # GET /food_products/1
  # GET /food_products/1.json
  def show
  end

  # GET /food_products/new
  def new
    @food_product = FoodProduct.new
  end

  # GET /food_products/1/edit
  def edit
  end

  # POST /food_products
  # POST /food_products.json
  def create
    @food_product = FoodProduct.new(food_product_params)

    respond_to do |format|
      if @food_product.save
        format.html { redirect_to @food_product, notice: 'Food product was successfully created.' }
        format.json { render :show, status: :created, location: @food_product }
      else
        format.html { render :new }
        format.json { render json: @food_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_products/1
  # PATCH/PUT /food_products/1.json
  def update
    respond_to do |format|
      if @food_product.update(food_product_params)
        format.html { redirect_to @food_product, notice: 'Food product was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_product }
      else
        format.html { render :edit }
        format.json { render json: @food_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_products/1
  # DELETE /food_products/1.json
  def destroy
    @food_product.destroy
    respond_to do |format|
      format.html { redirect_to food_products_url, notice: 'Food product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_product
      @food_product = FoodProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_product_params
      params.require(:food_product).permit(:group_id, :name, :first_day_num, :second_day_num, :is_cooking, :start)
    end

    def set_groups
      # ユーザが所有し，模擬店(食品販売)のカテゴリの団体を取得する
      super  # set @groups by GroupBase.get_groups
      @groups = @groups.where( group_category_id: 1)
    end
end

app/helpers/food_products_helper.rb
module FoodProductsHelper
end

app/views/food_products/_form.html.erb
<%= simple_form_for @food_product, wrapper: "horizontal_form", :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.association :group, collection: @groups, selected: @food_product.group_id %>
  <%= error_span(@food_product[:group_id]) %>

  <%= f.input :name, hint: t(".hint_name") %>
  <%= error_span(@food_product[:name]) %>

  <%= f.input :first_day_num, hint: t(".hint_first_day_num") %>
  <%= error_span(@food_product[:first_day_num]) %>
  <%= f.input :second_day_num, hint: t(".hint_second_day_num") %>
  <%= error_span(@food_product[:second_day_num]) %>

  <%= f.input :is_cooking,
    hint: t(".hint_is_cooking"),
    collection: [["調理あり", true],["調理なし(提供のみ)", false]],
    as: :radio_buttons
  %>
  <%= error_span(@food_product[:is_cooking]) %>

  <div class="alert alert-dismissible alert-warning">
    <h4>注意!</h4>
    <p>調理の有無は次のように選択して下さい．</p>
    <p><b>調理あり</b>：何らかの調理（料理・食品を直接覆うパッケージを開封など）が含まれるもの</p>
    <p><b>調理なし</b> ：上記に該当しない場合</p>
    <p>
      例1）調理した食品を販売・提供する場合：調理あり<br>
      例2）缶飲料等を開封し、紙コップで提供する場合：調理あり<br>
      例3）缶飲料等を開封せず、そのまま提供する場合：調理なし
    </p>
  </div>

  <%= error_span(@food_product[:num]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                food_products_path, :class => 'btn btn-default' %>
<% end %>

app/views/food_products/edit.html.erb
<%- model_class = FoodProduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/food_products/index.html.erb
<%- model_class = FoodProduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:group) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:first_day_num) %></th>
      <th><%= model_class.human_attribute_name(:second_day_num) %></th>
      <th><%= model_class.human_attribute_name(:is_cooking) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @food_products.each do |food_product| %>
      <tr>
        <td><%= food_product.group %></td>
        <td><%= food_product.name %></td>
        <td><%= food_product.first_day_num %></td>
        <td><%= food_product.second_day_num %></td>
        <td><%= food_product.disp_cooking %></td>
        <td>
          <%= show_edit_botton(edit_food_product_path(food_product), food_product) %>
          <%= show_destroy_botton(food_product_path(food_product), food_product) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.back', :default => t("helpers.links.back")),
              welcome_index_path, :class => 'btn btn-default'  %>
<%= show_new_with_group(FoodProduct, new_food_product_path) %>

app/views/food_products/new.html.erb
<%- model_class = FoodProduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/food_products/show.html.erb
<%- model_class = FoodProduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:group) %>:</strong></dt>
  <dd><%= @food_product.group %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @food_product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:first_day_num) %>:</strong></dt>
  <dd><%= @food_product.first_day_num %></dd>
  <dt><strong><%= model_class.human_attribute_name(:second_day_num) %>:</strong></dt>
  <dd><%= @food_product.second_day_num %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_cooking) %>:</strong></dt>
  <dd><%= @food_product.disp_cooking %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              food_products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_food_product_path(@food_product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              food_product_path(@food_product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>