config/routes.rb
Rails.application.routes.draw do
  resources :assign_rental_items do
    collection do
      get 'item_list'
    end
  end

  get 'health_check_pages/cooking'
  get 'health_check_pages/no_cooking'

  get 'stool_test_pages/check_sheet'
  get 'stool_test_pages/for_examiner_sheet'
  get 'stool_test_pages/for_health_center_sheet'

  resources :group_project_names
  resources :stage_common_options
  resources :rentable_items
  resources :stocker_items
  resources :sub_reps
  resources :purchase_lists do
    collection do
      get 'index_cooking'
      get 'new_cooking'
      get 'index_noncooking'
      get 'new_noncooking'
    end
  end
  resources :shops
  resources :food_products
  resources :employees
  resources :place_orders
  resources :stage_orders
  resources :power_orders
  resources :rental_orders
  resources :groups
  resources :user_details
  get 'welcome/index'
  get 'welcome/regist_user_detail'

  config = ActiveAdmin::Devise.config
  config[:controllers][:registrations] = 'registrations'
  devise_for :users, config
  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/models/sub_rep.rb
class SubRep < ActiveRecord::Base
  belongs_to :group
  belongs_to :department
  belongs_to :grade

  # 必須入力
  validates :group_id, :name_ja, :name_en, :tel, :email, :department_id, :grade_id,
    presence: true

  # 半角英字と半角スペースのみ
  validates :name_en, format: { with: /\A[a-zA-Z\s]+\z/i }

  # tel -> 半角数字とハイフンのみ, ( [333-4444-4444, for 携帯], [4444-22-4444, for 固定] )
  validates :tel, format: { with: /(\A\d{3}-\d{4}-\d{4}+\z)|(\A\d{4}-\d{2}-\d{4})+\z/i }

  validates :email, :email_format => { :message => '有効なe-mailアドレスを入力してください' }
end

app/controllers/sub_reps_controller.rb
class SubRepsController < GroupBase
  before_action :set_sub_rep, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource # for cancancan

  # GET /sub_reps
  # GET /sub_reps.json
  def index
    @sub_reps = SubRep.where(group_id: @groups)
  end

  # GET /sub_reps/1
  # GET /sub_reps/1.json
  def show
  end

  # GET /sub_reps/new
  def new
    @sub_rep = SubRep.new
  end

  # GET /sub_reps/1/edit
  def edit
  end

  # POST /sub_reps
  # POST /sub_reps.json
  def create
    @sub_rep = SubRep.new(sub_rep_params)

    respond_to do |format|
      if @sub_rep.save
        format.html { redirect_to @sub_rep, notice: 'Sub rep was successfully created.' }
        format.json { render :show, status: :created, location: @sub_rep }
      else
        format.html { render :new }
        format.json { render json: @sub_rep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_reps/1
  # PATCH/PUT /sub_reps/1.json
  def update
    respond_to do |format|
      if @sub_rep.update(sub_rep_params)
        format.html { redirect_to @sub_rep, notice: 'Sub rep was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_rep }
      else
        format.html { render :edit }
        format.json { render json: @sub_rep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_reps/1
  # DELETE /sub_reps/1.json
  def destroy
    @sub_rep.destroy
    respond_to do |format|
      format.html { redirect_to sub_reps_url, notice: 'Sub rep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_rep
      @sub_rep = SubRep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_rep_params
      params.require(:sub_rep).permit(:group_id, :name_ja, :name_en, :department_id, :grade_id, :tel, :email)
    end
end

app/helpers/sub_reps_helper.rb
module SubRepsHelper
end

app/views/sub_reps/_form.html.erb
<%= simple_form_for @sub_rep, wrapper: "horizontal_form", :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.association :group, collection: @groups, selected: @sub_rep.group_id %>
  <%= error_span(@sub_rep[:group_id]) %>

  <%= f.input :name_ja,
    hint: t(".hint_name_ja")
    %>
  <%= error_span(@sub_rep[:name_ja]) %>

  <%= f.input :name_en,
    hint: t(".hint_name_en")
  %>
  <%= error_span(@sub_rep[:name_en]) %>

  <%= f.association :department, label_method: :name_ja %>
  <%= error_span(@sub_rep[:department_id]) %>

  <%= f.association :grade, label_method: :name %>
  <%= error_span(@sub_rep[:grade_id]) %>

  <%= f.input :tel,
    hint: t(".hint_tel")
  %>
  <%= error_span(@sub_rep[:tel]) %>

  <%= f.input :email %>
  <%= error_span(@sub_rep[:email]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sub_reps_path, :class => 'btn btn-default' %>
<% end %>

app/views/sub_reps/edit.html.erb
<%- model_class = SubRep -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sub_reps/index.html.erb
<%- model_class = SubRep -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%# 副代表未登録の警告 %>
<%= render partial: 'shared/warning_subrep' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:group_name) %></th>
      <th><%= model_class.human_attribute_name(:name_ja) %></th>
      <th><%= model_class.human_attribute_name(:name_en) %></th>
      <th><%= model_class.human_attribute_name(:department) %></th>
      <th><%= model_class.human_attribute_name(:grade) %></th>
      <th><%= model_class.human_attribute_name(:tel) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sub_reps.each do |sub_rep| %>
      <tr>
        <td><%= sub_rep.group.name %></td>
        <td><%= sub_rep.name_ja %></td>
        <td><%= sub_rep.name_en %></td>
        <td><%= sub_rep.department.name_ja %></td>
        <td><%= sub_rep.grade.name %></td>
        <td><%= sub_rep.tel %></td>
        <td><%= sub_rep.email %></td>
        <td>
          <%= link_to t('.detail', :default => t("helpers.links.show")),
                      sub_rep_path(sub_rep), :class => 'btn btn-default btn-xs' %>
          <%= show_edit_botton(edit_sub_rep_path(sub_rep), sub_rep) %>
          <%= show_destroy_botton(sub_rep_path(sub_rep), sub_rep) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.back', :default => t("helpers.links.back")),
              welcome_index_path, :class => 'btn btn-default'  %>
<%= show_new_with_group(SubRep, new_sub_rep_path) %>

app/views/sub_reps/new.html.erb
<%- model_class = SubRep -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sub_reps/show.html.erb
<%- model_class = SubRep -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:group_id) %>:</strong></dt>
  <dd><%= @sub_rep.group_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_ja) %>:</strong></dt>
  <dd><%= @sub_rep.name_ja %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_en) %>:</strong></dt>
  <dd><%= @sub_rep.name_en %></dd>
  <dt><strong><%= model_class.human_attribute_name(:department_id) %>:</strong></dt>
  <dd><%= @sub_rep.department_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:grade_id) %>:</strong></dt>
  <dd><%= @sub_rep.grade_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tel) %>:</strong></dt>
  <dd><%= @sub_rep.tel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @sub_rep.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              sub_reps_path, :class => 'btn btn-default'  %>
<%= show_edit_botton(edit_sub_rep_path(@sub_rep), @sub_rep) %>
<%= show_destroy_botton(sub_rep_path(@sub_rep), @sub_rep) %>